import React from 'react'
import '../../styles/mine.css'

function About() {
  return (
    <div className='about-page'>
      <h3 className='about-head'>About Us</h3>
<p id='pp'>Waste generated in cities of emerging economies is growing faster than ever. Kisumu, produces nearly 1 million tons of solid waste annually. Already facing antiquated waste management systems and using over-capacity landfill spaces, most of the waste is illegally dumped especially diapers, creating a devastating impact on the environment and public health.In line with Kenya’s development blueprint (Vision 2030) and its guiding principle of reducing the effects of waste in cities, ADM uses modern technologies to offer high quality waste management services which include segregation, collection, removal and overall support towards reduction of diapers generated by homes and businesses.</p>
    </div>
  )
}

export default About
